name: project_soma
description: "Soma is a lightweight desktop application built with Flutter, designed to simplify financial management and provide total control over your cash flow."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.4.0+2
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_masked_text2: ^0.9.1
  intl: ^0.20.2
  get_it: ^9.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
