sonar.projectKey=alysonGuimaraes_Project-Soma
sonar.organization=alysonguimaraes

sonar.projectName=Project-Soma
sonar.projectVersion=1.0

sonar.sources=lib
sonar.tests=test

sonar.sourceEncoding=UTF-8

sonar.exclusions=android/**, ios/**, windows/**, build/**, .dart_tool/**, **/*.g.dart, **/*.freezed.dart, lib/generated_plugin_registrant.dart

sonar.dart.lcov.reportPath=coverage/lcov.info
