// Mocks generated by Mockito 5.4.6 from annotations
// in project_soma/test/features/transaction/mocks/transaction_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:project_soma/features/transaction/domain/entities/transaction.dart'
    as _i4;
import 'package:project_soma/features/transaction/domain/entities/transaction_filter.dart'
    as _i5;
import 'package:project_soma/features/transaction/domain/repository/i_transaction_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ITransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITransactionRepository extends _i1.Mock
    implements _i2.ITransactionRepository {
  MockITransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TransactionEntity>?> getTransactionsByFilter(
    _i5.TransactionFilter? filter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByFilter, [filter]),
            returnValue: _i3.Future<List<_i4.TransactionEntity>?>.value(),
          )
          as _i3.Future<List<_i4.TransactionEntity>?>);

  @override
  _i3.Future<_i4.TransactionEntity?> getTransactionById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionById, [id]),
            returnValue: _i3.Future<_i4.TransactionEntity?>.value(),
          )
          as _i3.Future<_i4.TransactionEntity?>);

  @override
  _i3.Future<List<_i4.TransactionEntity>> getTransactionsByMonthYear(
    String? monthYear,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByMonthYear, [monthYear]),
            returnValue: _i3.Future<List<_i4.TransactionEntity>>.value(
              <_i4.TransactionEntity>[],
            ),
          )
          as _i3.Future<List<_i4.TransactionEntity>>);

  @override
  _i3.Future<void> createTransaction(_i4.TransactionEntity? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTransaction(_i4.TransactionEntity? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
